### ISSUE TITLE
select only inside the interval

### ISSUE THREAD

**Issue by berkson** [Marco4763/smart_calendar#1]
It will be nice if the calendar only showed the days between the initial date and last date interval.
the way that is we can select any date before or after and if we click at the name of the month It shows the snack calendar leaving the user go back a month and select there too.
It's  a nice widget, but I think that this function will add to it.

**Comment by marcoedomingos** [comment]
Hello Berkson, thank you for the sugestion, this will be added on the next release.

**Comment by marcoedomingos** [comment]
Solved! Check the smart_calendar: 0.0.2  release.
